version: '3'
services:
  cloudflare-dns-tls:
    build: .
    image: qmcgaw/cloudflare-dns-server
    container_name: cloudflare-dns-tls
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=0
      - BLOCK_MALICIOUS=off
      - LISTENINGPORT=53
      - PROVIDER=cloudflare
    ports:
      - 53:53/udp
    network_mode: bridge
    restart: always
